//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika07
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobActorsTheatre
    {
        public int ID_job { get; set; }
        public Nullable<int> Actor { get; set; }
        public Nullable<int> Spectakl { get; set; }
        public string Role { get; set; }
        public Nullable<decimal> CostContract { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Spektakli Spektakli { get; set; }
    }
}
