//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika07
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBGoglickEntities : DbContext
    {

        private static DBGoglickEntities _context;

        public DBGoglickEntities()
            : base("name=DBGoglickEntities")
        {
        }

        public static DBGoglickEntities GetContext() 
        {
            if (_context == null)
                _context = new DBGoglickEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<JobActorsTheatre> JobActorsTheatre { get; set; }
        public virtual DbSet<Spektakli> Spektakli { get; set; }
    }
}
